### ISSUE TITLE
unpickling error 

### ISSUE THREAD

**Issue by baselqt** [ibaiGorordo/ONNX-ImageNet-1K-Object-Detector#4]
i try running the image script but i get this error 
(venv) d:\objdet>D:\objdet\venv\Scripts\python.exe image_object_detection.py
Traceback (most recent call last):
  File "d:\objdet\image_object_detection.py", line 19, in <module>
    detector = Detector1K(detection_model_path, classification_model_path, detection_threshold, classification_threshold)
  File "d:\objdet\detector1K\detector1K.py", line 26, in __init__
    self.classifier = Resnet50Classifier(classifier_model_path, classifier_threshold)
  File "d:\objdet\detector1K\resnet50Classifier.py", line 24, in __init__
    self.load_label_dict()
  File "d:\objdet\detector1K\resnet50Classifier.py", line 41, in load_label_dict
    self.clsid_to_label_dict = pickle.load(f)
_pickle.UnpicklingError: the STRING opcode argument must be quoted

**Comment by baselqt** [comment]
it might be due to incompatible python version, what version did you use to run it?
