### ISSUE TITLE
ONNXRuntimeError

### ISSUE THREAD

**Issue by hf62580** [ibaiGorordo/ONNX-ImageNet-1K-Object-Detector#5]
Hello Author,
I encountered the following error during inference. Could this be an issue with the ONNXRuntime version? I am using ONNXRuntime version 1.7.1.

/root/anaconda3/envs/oln/bin/python /mnt/myDisk/deepLearn/ONNX-ImageNet-1K-Object-Detector-main/main/image_object_detection.py
Traceback (most recent call last):
  File "/mnt/myDisk/deepLearn/ONNX-ImageNet-1K-Object-Detector-main/main/image_object_detection.py", line 36, in <module>
    detections = detector(image)
  File "/mnt/myDisk/deepLearn/ONNX-ImageNet-1K-Object-Detector-main/main/detector1K/detector1K.py", line 33, in __call__
    return self.detect_objects(image)
  File "/mnt/myDisk/deepLearn/ONNX-ImageNet-1K-Object-Detector-main/main/detector1K/detector1K.py", line 48, in detect_objects
    outputs = self.inference(input_tensor)
  File "/mnt/myDisk/deepLearn/ONNX-ImageNet-1K-Object-Detector-main/main/detector1K/detector1K.py", line 74, in inference
    outputs = self.session.run(self.output_names, {self.input_name: input_tensor})
  File "/root/anaconda3/envs/oln/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 188, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(float)) , expected: (tensor(uint8))

**Comment by shiqicai** [comment]
I think the problem is the author didn't specify the exact versions in requirements.txt. With time goes by, we are had to run it with the newest envs.
